Assert value check's replaced by error's
kentik/community_sdk_python pull request #106
Opened 2022-02-01 14:53 UTC by jdziurzynski

Issue : KNTK-40

Replaced "assert" statements with suitable exceptions e.g. `IncompleteObjectError`. "assert" statements evaluates only in debug mode.

2022-02-02 16:51 UTC, danielfurman requested changes

2022-02-02 16:51 UTC, danielfurman commented on kentik_api_library/kentik_api/api_resources/custom_dimensions_api.py
> +            raise IncompleteObjectError("Custom Dimensions", "custom dimension name value is required")
```suggestion
            raise IncompleteObjectError("Custom Dimensions", "name is required")
```
In other places too.

2022-02-03 07:57 UTC, mmac-m3a commented on kentik_api_library/kentik_api/api_resources/custom_applications_api.py
> +            raise IncompleteObjectError("Custom Aplication", "custom aplication name is required")
Consider refactoring the exception to take class instance as the first argument. With that you can use `obj.__class__.__name__` to get the class name. So, the code would look like this:

```
raise IncompleteObjectError(custom_application, "name is required")
```

We may also consider meta-programming the validation by giving each class a list of constraints. Something like this (using `CustomApplication` as an example):

```python
class CustomApplication:
    CONSTRAINTS = [
        {"attr": "name", "validator": lambda x: x is not None, "msg": "name is required"} 
    ]
   ...

def validate_object(obj: Any):
    if not hasattr(obj, CONSTRAINTS):
        return
    for c in obj.CONSTRAINTS:
       if not hasattr(obj, c["attr"]):
           raise InvalidConstraint(c, f"class {c.__class__.__name__} has no attribute {c['attr']")
       if not c["validator"](getattr(obj, c["name"):
           raise IncompleteObjectError(obj, c["msg"])
``` 
(we will obviously need to create the `InvalidConstraint` exception)

The code here will look like this:

```python
def create(self, custom_application: CustomApplication) -> CustomApplication:
    validate_object(custom_application)
    ...
```

2022-02-03 12:32 UTC, danielfurman commented on kentik_api_library/kentik_api/api_resources/custom_applications_api.py
> +            raise IncompleteObjectError("Custom Aplication", "custom aplication name is required")
@mmac-m3a I created a task for making validation code consistent across resources (https://clkentik.atlassian.net/browse/KNTK-386). Your suggestion could be applied as a part of that. However for me it seems too magic.

2022-02-03 14:54 UTC, jdziurzynski commented on kentik_api_library/kentik_api/api_resources/custom_applications_api.py
> +            raise IncompleteObjectError("Custom Aplication", "custom aplication name is required")
After conversation with Daniel and Mateusz, I created a task regarding to exceptions https://clkentik.atlassian.net/browse/KNTK-388

2022-02-04 18:10 UTC, danielfurman commented on kentik_api_library/kentik_api/api_resources/custom_dimensions_api.py
> +    def check_fields(populator: Populator):
Ticket: https://clkentik.atlassian.net/browse/KNTK-386

2022-02-04 18:10 UTC, danielfurman commented on kentik_api_library/kentik_api/api_resources/custom_dimensions_api.py
> +            raise IncompleteObjectError("Populators", "value is required")
Done

2022-02-04 18:10 UTC, danielfurman commented on kentik_api_library/kentik_api/api_resources/custom_dimensions_api.py
> +            raise IncompleteObjectError("Custom Dimensions", "custom dimension name value is required")
Done

2022-02-04 18:11 UTC, danielfurman approved these changes

2022-02-08 04:15 UTC, mmac-m3a commented on kentik_api_library/kentik_api/api_resources/custom_applications_api.py
> +            raise IncompleteObjectError("Custom Aplication", "custom aplication name is required")
I don't quite see what is magic about having validation constraints associated with data representation. There are surely different ways to implement it and I by no means insist on the very code I've proposed. I though prefer a solution that eliminates repetitive code and ideally makes validations logic easy to understand.

2022-02-08 04:22 UTC, mmac-m3a submitted a review, later dismissed

2022-02-08 04:46 UTC, mmac-m3a commented
I'm glad to see that our CI tests are more careful than me :). "String" or "string" are really not valid Python types (or objects in the app). Please, run `mypy` (`python3 setup.py mypy`) on the repo and fix all problems.

2022-02-08 09:28 UTC, danielfurman approved these changes

2022-02-16 22:24 UTC, mmac-m3a approved these changes

2022-02-16 22:25 UTC, merged