Consistent payload validation
kentik/community_sdk_python pull request #108
Opened 2022-02-24 09:47 UTC by jdziurzynski

KNTK - 386
https://clkentik.atlassian.net/browse/KNTK-386

All payload validation located in /api_resources moved to requests_payload.
To make this validation consistent also refactored create/update classes in /api_resources.

2022-03-04 18:33 UTC, danielfurman requested changes

2022-03-04 18:33 UTC, danielfurman commented on kentik_api_library/kentik_api/requests_payload/populators_payload.py
> +class PopulatorPayload:
We already have top level populator payload dataclass  called `_Populator`. After this change we'll have 2, which is confusing. I don't think it is a right direction. We need at least some naming convention let reader understand purpose of those 2 payload classes.

2022-03-04 18:33 UTC, danielfurman commented on kentik_api_library/kentik_api/requests_payload/saved_filters_payload.py
> +def check_fields(saved_filter: SavedFilter, method: str):
```suggestion
def validate(saved_filter: SavedFilter, method: str):
```

2022-03-08 08:25 UTC, jdziurzynski commented on kentik_api_library/kentik_api/api_resources/tags_api.py
> -        if tag.flow_tag is None:
The main purpose of the task was to move payload validation to request_payload layer. Given check was duplicated, it was already also in https://github.com/jdziurzynski/community_sdk_python/blob/06ed555b1fd3118683d39e4f97aa830732e2e8a8/kentik_api_library/kentik_api/requests_payload/tags_payload.py#L150

2022-03-09 03:26 UTC, mmac-m3a commented
I'll wait for @danielfurman  to approve.

2022-03-15 16:14 UTC, danielfurman commented on kentik_api_library/kentik_api/requests_payload/custom_dimensions_payload.py
> +        check_fields(custom_dimension, "Create")
Done

2022-03-15 16:14 UTC, danielfurman commented on kentik_api_library/kentik_api/requests_payload/populators_payload.py
> +        check_fields(populator, "Create")
Done

2022-03-15 16:17 UTC, danielfurman commented on kentik_api_library/kentik_api/api_resources/tags_api.py
> -        if tag.flow_tag is None:
Ok, I didn't notice that.

2022-03-15 16:17 UTC, danielfurman commented on kentik_api_library/kentik_api/requests_payload/custom_applications_payload.py
> +    """This datastructure represents JSON CustomApplication payload as it is transmitted to and from KentikAPI"""
Done

2022-03-15 16:18 UTC, danielfurman commented on kentik_api_library/kentik_api/requests_payload/custom_dimensions_payload.py
> +    """This datastructure represents JSON CustomDimension payload as it is transmitted to and from KentikAPI"""
Done

2022-03-15 16:18 UTC, danielfurman commented on kentik_api_library/kentik_api/requests_payload/populators_payload.py
> +    """This datastructure represents JSON Populator payload as it is transmitted to and from KentikAPI"""
Done

2022-03-15 16:19 UTC, danielfurman commented on kentik_api_library/kentik_api/requests_payload/populators_payload.py
> +class PopulatorPayload:
After the changes, PopulatorPayload and PopulatorGetPayload is acceptable for me.

2022-03-15 16:20 UTC, danielfurman approved these changes

2022-03-22 18:22 UTC, mmac-m3a approved these changes
LGTM

2022-03-22 18:22 UTC, merged