Remove default date strings from api v5
kentik/community_sdk_python pull request #120
Opened 2022-06-14 09:06 UTC by mateuszmidor

KNTK-407

- remove default date strings from api v5

2022-06-14 14:33 UTC, danielfurman requested changes

2022-06-14 14:33 UTC, danielfurman commented on kentik_api_library/kentik_api/public/device_label.py
The discussion involved adding getters for optional datetime: `def created(self) -> Optional[datetime]:` I think that they are much more usable than a string `def created_date(self) -> str:`. I would leave only getters returning datetime, as I don't see a reason for keeping 2 variants per field.
I think that this PR is a good place to do that (probably for all resources that have properties with dates)

2022-06-20 12:14 UTC, danielfurman approved these changes

2022-06-20 13:56 UTC, jdziurzynski approved these changes

2022-06-23 05:52 UTC, mmac-m3a approved these changes
LGTM.

2022-06-23 06:08 UTC, mmac-m3a commented
Looks like isort is unhappy. Please fix.

2022-06-23 15:35 UTC, danielfurman approved these changes

2022-07-07 04:44 UTC, mmac-m3a approved these changes

2022-07-07 04:46 UTC, merged