Implemented My Kentik Portal API methods
kentik/community_sdk_python pull request #32
Opened 2020-12-21 15:09 UTC by lukaa12

2020-12-21 15:43 UTC, TedatKentik requested changes
Do we need to update our code-tests for this?
kentik-api / code-tests (3.7) (pull_request) Failing after 40s
kentik-api / code-tests (3.8) (pull_request) Cancelled after 44s — code-tests (3.8)

example
==
would reformat /github/workspace/kentik_api_library/kentik_api/public/tenant.py
would reformat /github/workspace/kentik_api_library/kentik_api/requests_payload/tenants_payload.py
Oh no! 💥 💔 💥
2 files would be reformatted, 102 files would be left unchanged.
Error: The operation was canceled.

@lukaa12 , @boscard , let me know what needs to be merged, to facilitate demo tomorrow.

2020-12-22 07:43 UTC, lukaa12 commented
I manually reformatted files marked by black to refactor. I think our code-tests are fine. As far as I am concerned this PR is not necessary for today's demo.

2020-12-22 13:43 UTC, mateuszmidor approved these changes

2020-12-22 19:31 UTC, TedatKentik approved these changes
extending tenants in API

2020-12-22 19:32 UTC, merged