Moved tests from component to unit directory
kentik/community_sdk_python pull request #47
Opened 2021-01-18 11:01 UTC by lukaa12

2021-01-18 11:16 UTC, mateuszmidor requested changes
please reflect the src dir tree under tests dir tree so we dont end up with one big all-unittests directory

2021-01-18 14:28 UTC, mateuszmidor approved these changes

2021-01-19 16:47 UTC, Fenthick approved these changes

2021-01-19 19:38 UTC, TedatKentik approved these changes
Moving components for tests towards unit tests

2021-01-19 19:38 UTC, merged