Reorganized User class from public to avoid optionals.
kentik/community_sdk_python pull request #68
Opened 2021-02-15 15:20 UTC by lukaa12

KNTK-180

2021-02-16 09:13 UTC, mateuszmidor submitted a review, later dismissed

2021-02-22 13:34 UTC, Fenthick requested changes

2021-02-25 07:50 UTC, Fenthick approved these changes

2021-02-25 08:07 UTC, mateuszmidor approved these changes

2021-02-25 13:47 UTC, TedatKentik approved these changes
reorganized user class - no longer public - avoids optionals

2021-02-25 13:47 UTC, merged